blank_issues_enabled: true
contact_links:
  - name: 🤔 Long question or ideas?
    url: https://github.com/INeedJobToStartWork/Ghost-ink/discussions
    about: Ask long-form questions and discuss ideas.
